---
deployment:
  tasks:
    - export DEPLOYPATH=/home/growthrocket/public_html/wp-content/plugins/acf-analyzer
    - /bin/cp -R * $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;